String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> (or swipe on mobile) to move the tiles. When two matching cupcakes touch, they <strong>merge into the next flavor!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> Inspired by the classic <a href=\"https://play2048.co/\" target=\"_blank\" rel=\"noopener noreferrer\">2048</a> puzzle by Gabriele Cirulli (MIT License). Built as a free browser game with extras like undo, sound, and daily challenges.",
    "%credits"              : "Cupcake photography style inspired by bakery dessert aesthetics. Not affiliated with any bakery brand.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048 Cupcakes #2048Cupcakes",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolate peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : 'Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p2'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : 'Confetti Vanilla',
    '%p8192'                : 'Rainbow'
	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> (or swipe on mobile) to move the tiles. When two matching cupcakes touch, they <strong>merge into the next flavor!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> Inspired by the classic <a href=\"https://play2048.co/\" target=\"_blank\" rel=\"noopener noreferrer\">2048</a> puzzle by Gabriele Cirulli (MIT License). Built as a free browser game with extras like undo, sound, and daily challenges.",
    "%credits"              : "Cupcake photography style inspired by bakery dessert aesthetics. Not affiliated with any bakery brand.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048 Cupcakes #2048Cupcakes",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolate peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : 'Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p2'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : 'Confetti Vanilla',
    '%p8192'                : 'Rainbow'
  }

});
